---
layout: default
title: Home
---

# Samuel Hor
Solar physics PhD student.

**Navigation:** [Home](/) | [About](/about/) | [Teaching](/teaching/) | [Research](/research/) | [Publications](/publications/) | [Contact](/contact/)

Welcome to my website...
