remote_theme: pages-themes/modernist@v0.2.0
title: Samuel Hor
description: [Awards](/awards/) | [Education](/education/) | [Teaching](/teaching/)
plugins:
  - jekyll-remote-theme

header_pages:
  - Awards.md
  - Education.md
  - Teaching.md
