remote_theme: pages-themes/modernist@v0.2.0
title: Samuel Hor
description: Solar Physics PhD Student
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

header_pages:
  - Teaching.md
