remote_theme: pages-themes/modernist@v0.2.0
title: Samuel Hor
description: Solar Physics PhD Student
plugins:
  - jekyll-remote-theme

header_pages:
  - Awards.md
  - Education.md
  - Experience.md
  - Teaching.md
  - Volunteering.md
